phar: contao-manager.phar

tasks:
  - type: run-process
    command: "%package:contao/contao-manager%/node_modules/.bin/gulp --production"
  - type: run-process
    command: "%package:contao/contao-manager%/app/console cache:clear --env=phar --no-debug --no-warmup"
  - type: run-process
    command: "%package:contao/contao-manager%/app/console cache:warmup --env=phar --no-debug"
  - type: add-package
    name: contao/contao-manager
    exclude_dependencies:
      # exclude everything needed for PHP<5.5, we are min php 5.5.
      - ircmaxell/password-compat
      - symfony/polyfill-php54
      - symfony/polyfill-php55
      # exclude build time related dependencies.
      - seld/phar-utils
    include_files: &default_include_files
      - "*.php"
      - "*.twig"
      - "(LICENSE\\.?.*)"
      - "%package:contao/contao-manager%/app/console"
    exclude_files: &default_exclude_files
      - "(.*\\/[Tt]ests?\\/*)"
      - "*tests/*.php"
    package_override:
      contao/contao-manager:
        exclude_files:
          - *default_exclude_files
          - "app/cache/prod/*"
          - "app/cache/test/*"
          - "((node_modules|assets)/*)"
        include_files:
          - *default_include_files
          - "(src/Resources/public/*)"
      composer/composer:
        exclude_files:
          - *default_exclude_files
          - bootstrap.php
          - src/Compiler.php
        include_files:
          - *default_include_files
          - "(res/*)"
      seld/cli-prompt:
        include_files:
          - *default_include_files
          - "*hiddeninput.exe"
      symfony/framework-bundle:
        exclude_files:
          - *default_exclude_files
          # Drop all commands registered by symfony bundle as we can not use them.
          - "(Command/.*(Config|Assets|Cache|Debug|Router|Server|Translation|YamlLint).*Command\\.php)"
          # Drop all views, we are not using symfony forms.
          - "*views*"
      symfony/security-bundle:
        exclude_files:
          - *default_exclude_files
          # Drop all commands registered by symfony bundle as we can not use them.
          - "(Command/.*AclCommand\\.php)"
      tenside/core-bundle:
        exclude_files:
          - *default_exclude_files
          # Drop the stub.
          - "src/Resources/stub.php"

  - type: set-stub
    stub_file: "%package:tenside/core-bundle%/src/Resources/stub.php"

  - type: composer-autoload
    optimize: true

rewrites:
  - files:
      - "%package:contao/contao-manager%/app/console"
    filter:
      - type: replace
        "#!/usr/bin/env php": ""
  - files:
      - "%package:tenside/core-bundle%/src/Resources/stub.php"
      - "%package:tenside/core%/src/Tenside.php"
    filter:
      - type: replace
        "@@TENSIDE_MIN_PHP_VERSION@@": "5.6.0"

      - type: warning-time
        search: "@warning_time@"
        format: "@@warning_time@@"
        # 30 * 86400 = 2592000
        ahead: 2592000

      - type: replace
        "@package_version@": "%version:contao/contao-manager%"

      - type: replace
        "@tenside_distribution@": "contao/contao-manager"

      - type: replace
        "@release_date@": "%date:contao/contao-manager%"
      - type: replace
        "tenside.phar": "contao-manager.phar"
  - files:
      - "%package:contao/contao-manager%/app/cache/phar/*.php"
    filter:
      - type: replace
        "%package:contao/contao-manager%": "phar://contao-manager.phar"

  # keep this last
  - files: "*.php"
    filter:
      - type: php-strip
