language: php

php:
  - "5.6"
  - "7.0"
  - "nightly"

sudo: false

# Let's bump node.js to the latest version.
before_install:
   - nvm install node

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist --no-interaction
  - travis_retry npm install --no-progress

script:
  - ant -keep-going
  - ./vendor/bin/pharpiler compile -vvv
  - ./contao-manager.phar

# Hack to make things work again - we can not use a shallow repository.
git:
  depth: 2147483647

cache:
  directories:
    - vendor
