services:
    contao_manager.command.about:
        class: Contao\ManagerApi\Command\AboutCommand
        calls:
            - [setContainer, ["@service_container"]]

    contao_manager.command.integrity_check:
        class: Contao\ManagerApi\Command\IntegrityCheckCommand
        calls:
            - [addIntegrityCheck, ["@contao_manager.integrity.memory_limit"]]
            - [addIntegrityCheck, ["@contao_manager.integrity.allow_url_fopen"]]
            - [addIntegrityCheck, ["@contao_manager.integrity.systempdir"]]
            - [addIntegrityCheck, ["@contao_manager.integrity.php_extension"]]
            - [addIntegrityCheck, ["@contao_manager.integrity.symlink"]]
            - [addIntegrityCheck, ["@contao_manager.integrity.process"]]

    contao_manager.command.task_abort:
        class: Contao\ManagerApi\Command\TaskAbortCommand
        arguments: ["@contao_manager.task_manager"]

    contao_manager.command.task_delete:
        class: Contao\ManagerApi\Command\TaskDeleteCommand
        arguments: ["@contao_manager.task_manager"]

    contao_manager.command.task_update:
        class: Contao\ManagerApi\Command\TaskUpdateCommand
        arguments: ["@contao_manager.task_manager"]

    contao_manager.command.update:
        class: Contao\ManagerApi\Command\UpdateCommand
        calls:
            - [setContainer, ["@service_container"]]
