services:
    contao_manager.command.about:
        class: Contao\ManagerApi\Command\AboutCommand
        calls:
            - [setContainer, ["@service_container"]]

    contao_manager.command.integrity_check:
        class: Contao\ManagerApi\Command\IntegrityCheckCommand
        calls:
            - [addIntegrityCheck, ["@contao_manager.integrity.memory_limit"]]
            - [addIntegrityCheck, ["@contao_manager.integrity.allow_url_fopen"]]
            - [addIntegrityCheck, ["@contao_manager.integrity.openssl"]]
            - [addIntegrityCheck, ["@contao_manager.integrity.intl"]]
            - [addIntegrityCheck, ["@contao_manager.integrity.process"]]

    contao_manager.command.update:
        class: Contao\ManagerApi\Command\UpdateCommand
        calls:
            - [setContainer, ["@service_container"]]
