services:
    Contao\ManagerApi\Controller\SessionController:
        arguments:
            - "@contao_manager.config.user"
            - "@contao_manager.security.jwt_manager"
            - "@security.password_encoder"
        calls:
            - [setContainer, ["@service_container"]]

    contao_manager.controller.config_auth:
            class: Contao\ManagerApi\Controller\ConfigController
            arguments:
                - "@contao_manager.config.auth"
            calls:
                - [setContainer, ["@service_container"]]

    contao_manager.controller.config_composer:
            class: Contao\ManagerApi\Controller\ConfigController
            arguments:
                - "@contao_manager.config.composer"
            calls:
                - [setContainer, ["@service_container"]]

    contao_manager.controller.config_manager:
        class: Contao\ManagerApi\Controller\ConfigController
        arguments:
            - "@contao_manager.config.manager"
        calls:
            - [setContainer, ["@service_container"]]

    Contao\ManagerApi\Controller\UserController:
        arguments:
            - "@contao_manager.config.user"
        calls:
            - [setContainer, ["@service_container"]]

    Contao\ManagerApi\Controller\TaskController:
        arguments:
            - "@contao_manager.task_manager"

    Contao\ManagerApi\Controller\FileController:
        arguments:
            - "@kernel"
            - "@filesystem"

    Contao\ManagerApi\Controller\Server\ConfigController:
        arguments:
            - "@contao_manager.config.manager"
            - "@contao_manager.system.server_info"
            - "@contao_manager.composer.environment"
            - "@contao_manager.i18n.translator"

    Contao\ManagerApi\Controller\Server\ComposerController:
        arguments:
            - "@kernel"

    Contao\ManagerApi\Controller\Contao\AccessKeyController:
        arguments:
            - "@contao_manager.process.contao_api"
