services:
    contao_manager.integrity.allow_url_fopen:
        class: Contao\ManagerApi\IntegrityCheck\AllowUrlFopenCheck
        arguments:
            - "@contao_manager.i18n.translator"

    contao_manager.integrity.graphics_lib:
        class: Contao\ManagerApi\IntegrityCheck\GraphicsLibCheck
        arguments:
            - "@contao_manager.i18n.translator"

    contao_manager.integrity.session:
        class: Contao\ManagerApi\IntegrityCheck\SessionCheck
        arguments:
            - "@contao_manager.i18n.translator"

    contao_manager.integrity.memory_limit:
        class: Contao\ManagerApi\IntegrityCheck\MemoryLimitCheck
        arguments:
            - "@contao_manager.i18n.translator"

    contao_manager.integrity.php_extension:
        class: Contao\ManagerApi\IntegrityCheck\PhpExtensionsCheck
        arguments:
            - "@contao_manager.i18n.translator"

    contao_manager.integrity.process:
        class: Contao\ManagerApi\IntegrityCheck\ProcessCheck
        arguments:
            - "@contao_manager.i18n.translator"

    contao_manager.integrity.symlink:
        class: Contao\ManagerApi\IntegrityCheck\SymlinkCheck
        arguments:
            - "@contao_manager.i18n.translator"

    contao_manager.integrity.web_root:
        class: Contao\ManagerApi\IntegrityCheck\WebRootCheck
        arguments:
            - "@contao_manager.i18n.translator"

    contao_manager.integrity.systempdir:
        class: Contao\ManagerApi\IntegrityCheck\SysTempDirCheck
        arguments:
            - "@contao_manager.i18n.translator"
