imports:
    - { resource: controllers.yml }
    - { resource: commands.yml }
    - { resource: listener.yml }
    - { resource: tasks.yml }
    - { resource: integrity.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    contao_manager.config.auth:
        class: Contao\ManagerApi\Config\AuthConfig
        arguments:
            - "@kernel"
            - "@filesystem"

    contao_manager.config.composer:
        class: Contao\ManagerApi\Config\ComposerConfig
        arguments:
            - "@kernel"
            - "@filesystem"

    contao_manager.config.manager:
        class: Contao\ManagerApi\Config\ManagerConfig
        arguments:
            - "@kernel"
            - "@filesystem"

    contao_manager.config.user:
        class: Contao\ManagerApi\Config\UserConfig
        arguments:
            - "@kernel"
            - "@security.password_encoder"
            - "@filesystem"

    contao_manager.composer.cloud_resolver:
        class: Contao\ManagerApi\Composer\CloudResolver
        calls:
            - [setLogger, ["@logger"]]
        tags:
            - { name: monolog.logger, channel: tasks }

    contao_manager.composer.environment:
        class: Contao\ManagerApi\Composer\Environment
        arguments:
            - "@kernel"
            - "@contao_manager.config.manager"

    contao_manager.i18n.translator:
        class: Contao\ManagerApi\I18n\Translator
        arguments:
            - "@request_stack"

    contao_manager.process.console_factory:
        class: Contao\ManagerApi\Process\ConsoleProcessFactory
        arguments:
            - "@kernel"
            - "@contao_manager.system.server_info"
            - "@logger"

    contao_manager.process.contao_api:
        class: Contao\ManagerApi\Process\ContaoApi
        arguments:
            - "@contao_manager.process.console_factory"

    contao_manager.process.contao_console:
        class: Contao\ManagerApi\Process\ContaoConsole
        arguments:
            - "@contao_manager.process.console_factory"

    contao_manager.security.jwt_manager:
        class: Contao\ManagerApi\Security\JwtManager
        arguments:
            - "@contao_manager.config.user"

    contao_manager.security.jwt_authenticator:
        class: Contao\ManagerApi\Security\JwtAuthenticator
        arguments:
            - "@contao_manager.security.jwt_manager"

    contao_manager.security.token_authenticator:
        class: Contao\ManagerApi\Security\TokenAuthenticator
        arguments:
            - "@contao_manager.config.user"

    contao_manager.security.user_provider:
        class: Symfony\Component\Security\Core\User\InMemoryUserProvider
        factory: [Contao\ManagerApi\Security\UserProviderFactory, createUserProvider]
        arguments:
            - "@contao_manager.config.user"

    contao_manager.self_update.updater:
        class: Contao\ManagerApi\SelfUpdate\Updater
        arguments:
            - "@kernel"
            - "@contao_manager.config.manager"

    contao_manager.system.server_info:
        class: Contao\ManagerApi\System\ServerInfo
        arguments:
            - "@contao_manager.system.ip_info"
            - "@contao_manager.config.manager"
            - "%kernel.root_dir%/Resources/config/servers.yml"

    contao_manager.system.ip_info:
        class: Contao\ManagerApi\System\IpInfo

    app.command.background_task:
        class: Terminal42\BackgroundProcess\Command\ProcessRunnerCommand
        tags:
            - { name: console.command }

###
# Override Tenside services to adjust for Contao Manager
###

    tenside.home:
        class:  Contao\ManagerApi\Tenside\HomePathDeterminator
        arguments:
            - "@kernel"

    tenside.config:
        class:          Tenside\Core\Config\TensideJsonConfig
        factory:        [Contao\ManagerApi\Tenside\JsonConfigFactory, create]
        arguments:      ["@tenside.home"]
        public:         true

    tenside.status:
        class:     Contao\ManagerApi\Tenside\InstallationStatusDeterminator
        arguments:
            - "@contao_manager.config.user"
            - "@tenside.home"
        public: true
