
services:
    contao_manager.task_manager:
        class: Contao\ManagerApi\Task\TaskManager
        arguments:
            - "@kernel"
            - "@contao_manager.task_locator"
            - "@filesystem"

    contao_manager.task_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        tags: ['container.service_locator']
        arguments:
            -
                "contao/install": "@contao_manager.task.contao_install"
                "contao/rebuild-cache": "@contao_manager.task.rebuild_cache"
                "composer/install": "@contao_manager.task.composer_install"
                "composer/dump-autoload": "@contao_manager.task.dump_autoload"
                "composer/require": "@contao_manager.task.composer_require"
                "composer/remove": "@contao_manager.task.composer_remove"
                "composer/update": "@contao_manager.task.composer_update"
                "manager/self-update": "@contao_manager.task.self_update"

    contao_manager.task.contao_install:
        class: Contao\ManagerApi\Task\Contao\ContaoInstallTask
        arguments:
            - "@kernel"
            - "@contao_manager.process.console_factory"
            - "@contao_manager.i18n.translator"
            - "@filesystem"

    contao_manager.task.composer_install:
        class: Contao\ManagerApi\Task\Composer\ComposerInstallTask
        arguments:
            - "@contao_manager.process.console_factory"
            - "@contao_manager.i18n.translator"

    contao_manager.task.composer_require:
        class: Contao\ManagerApi\Task\Composer\ComposerRequireTask
        arguments:
            - "@contao_manager.process.console_factory"
            - "@contao_manager.i18n.translator"

    contao_manager.task.composer_remove:
        class: Contao\ManagerApi\Task\Composer\ComposerRemoveTask
        arguments:
            - "@contao_manager.process.console_factory"
            - "@contao_manager.i18n.translator"

    contao_manager.task.composer_update:
        class: Contao\ManagerApi\Task\Composer\ComposerUpdateTask
        arguments:
            - "@contao_manager.process.console_factory"
            - "@contao_manager.i18n.translator"

    contao_manager.task.dump_autoload:
        class: Contao\ManagerApi\Task\Composer\DumpAutoloadTask
        arguments:
            - "@contao_manager.process.console_factory"
            - "@contao_manager.i18n.translator"

    contao_manager.task.rebuild_cache:
        class: Contao\ManagerApi\Task\Contao\RebuildCacheTask
        arguments:
            - "@kernel"
            - "@contao_manager.process.console_factory"
            - "@contao_manager.i18n.translator"
            - "@filesystem"

    contao_manager.task.self_update:
        class: Contao\ManagerApi\Task\Manager\SelfUpdateTask
        arguments:
            - "@contao_manager.process.console_factory"
            - "@contao_manager.i18n.translator"
            - "@contao_manager.self_update.updater"
