imports:
    - { resource: config.yml }

# Add twig in dev mode for nelmio docs
framework:
    templating:
      engines: ['php', 'twig']

nelmio_api_doc:
  name: Contao Manager
  sandbox:
    authentication:
      name: authorization
      delivery: http
      type: bearer
    body_format:
      formats: [json]
      default_format: json
    request_format:
      default_format: json
      formats:
        json: true
      method: accept_header

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: debug
            handler:      nested
        nested:
            type: service
            id:   "tenside.logger"
