imports:
    - { resource: config.yml }

# We need this for generating the API docs.
framework:
  templating:
    engines: ['php', 'twig']

nelmio_api_doc:
  name: Contao Package Manager
  sandbox:
    authentication:
      name: authorization
      delivery: http
      type: bearer
    body_format:
      formats: [json]
      default_format: json
    request_format:
      default_format: json
      formats:
        json: true
      method: accept_header
