# Api doc must be included first, as the catch all otherwise will override it.
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /assets/api-doc

_main:
    resource: routing.yml
