_main:
    resource: routing.yml

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /assets/api-doc

# Fallback to UI index if no route matches
catch_all:
    path:     /{catchall}
    methods:  [GET]
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: 'index'
        ignoreAttributes: true
    requirements:
        catchall: .+
