_main:
    resource: routing.yml

# Fallback to UI index if no route matches
catch_all:
    path:     /{catchall}
    methods:  [GET]
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: 'index'
        ignoreAttributes: true
    requirements:
        catchall: .+
