index:
    path:      /
    defaults:  { _controller: AppBundle:Ui:index }
    methods:  [GET]

app:
    path:      /{locale}/{app_path}
    defaults:  { _controller: AppBundle:Ui:app, app_path: '' }
    methods:   [GET]
    requirements:
        locale: en|de
        app_path: .+

asset:
    path:     /web-assets/{path}
    defaults: { _controller: AppBundle:Ui:asset }
    methods:  [GET]
    requirements:
        path: .+

translation:
    path:     /translation/{locale}/{domain}
    defaults: { _controller: AppBundle:Ui:translation }
    methods:  [GET]

TensideCoreBundle:
    resource: "@TensideCoreBundle/Resources/config/routing.yml"
    prefix: /api

# Fallback to UI index if no route matches
catch_all:
    path:     /{catchall}
    methods:  [GET]
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: 'index'
        ignoreAttributes: true
    requirements:
        catchall: .+
