index:
    path:      /
    defaults:  { _controller: AppBundle:Ui:index }
    methods:   [GET]

login:
    path:      /login
    defaults:  { _controller: AppBundle:Ui:login }
    methods:   [GET]

install:
    path:      /install
    defaults:  { _controller: AppBundle:Ui:install }
    methods:   [GET]

packages:
    path:      /packages
    defaults:  { _controller: AppBundle:Ui:packages }
    methods:   [GET]

search:
    path:      /search
    defaults:  { _controller: AppBundle:Ui:search }
    methods:   [GET]

asset:
    path:     /assets/{path}
    defaults: { _controller: AppBundle:Ui:asset }
    methods:  [GET]
    requirements:
        path: .+

TensideCoreBundle:
    resource: "@TensideCoreBundle/Resources/config/routing.yml"
    prefix: /api
