services:
    contao_manager.command.integrity_check:
        class: Contao\ManagerApi\Command\IntegrityCheckCommand
        calls:
            - [addIntegrityCheck, ["@contao_manager.integrity.memory_limit"]]
            - [addIntegrityCheck, ["@contao_manager.integrity.allow_url_fopen"]]
            - [addIntegrityCheck, ["@contao_manager.integrity.openssl"]]
            - [addIntegrityCheck, ["@contao_manager.integrity.process"]]
            - [addIntegrityCheck, ["@contao_manager.integrity.contao"]]
            - [addIntegrityCheck, ["@contao_manager.integrity.web_root"]]
            - [addIntegrityCheck, ["@contao_manager.integrity.windows"]]
        tags:
            - { name: console.command }
