imports:
    - { resource: parameters.yml }
    - { resource: services/services.yml }

# The secret is only required to sign fragment URLs which is not used
framework:
    secret: ''
    default_locale: en

security:
    providers:
        contao_manager_user_provider:
            id: contao_manager.security.user_provider

    encoders:
        Symfony\Component\Security\Core\User\UserInterface: bcrypt

    firewalls:
        api:
            stateless: true
            guard:
                authenticators:
                    - contao_manager.security.jwt_authenticator
            anonymous: ~

    access_control:
        - { path: ^/api/(status|session), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
