imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/api.log"
            level: INFO
            channels: [!event]
            max_files: 10
