imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
    - { resource: listener.yml }

# The secret is only required to sign fragment URLs which is not used
framework:
    secret: ''

security:
    providers:
        tenside_core_user_provider:
            id: tenside.user_provider

    encoders:
        Symfony\Component\Security\Core\User\UserInterface: bcrypt

    firewalls:
        public:
            pattern: ^/api/(status|install/configure)$
            stateless: true
            simple_preauth:
                authenticator: tenside.jwt_authenticator
            anonymous: ~

        # Allow basic auth and token auth on login route.
        login:
            pattern: ^/api/auth$
            stateless: true
            simple_preauth:
                authenticator: tenside.jwt_authenticator
            guard:
                authenticators:
                    - app.postdata_authenticator

        # Allow only token auth on any API.
        secured_area:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: tenside.jwt_authenticator
