services:
    contao_manager.controller.status:
        class: Contao\ManagerApi\Controller\StatusController
        arguments:
            - "@kernel"
            - "@contao_manager.config.manager"
            - "@contao_manager.config.auth"
            - "@contao_manager.config.user"
            - "@contao_manager.process.contao_api"
            - "@filesystem"
        calls:
            - [setContainer, ["@service_container"]]
            - [addIntegrityCheck, ["@contao_manager.integrity.allow_url_fopen"]]
            - [addIntegrityCheck, ["@contao_manager.integrity.openssl"]]
            - [addIntegrityCheck, ["@contao_manager.integrity.proc_open"]]
            - [addIntegrityCheck, ["@contao_manager.integrity.contao"]]
            - [addIntegrityCheck, ["@contao_manager.integrity.web_root"]]
            - [addIntegrityCheck, ["@contao_manager.integrity.windows"]]

    contao_manager.controller.session:
        class: Contao\ManagerApi\Controller\SessionController
        arguments:
            - "@contao_manager.config.user"
            - "@contao_manager.security.jwt_manager"
            - "@security.password_encoder"
        calls:
            - [setContainer, ["@service_container"]]

    contao_manager.controller.config_auth:
            class: Contao\ManagerApi\Controller\ConfigController
            arguments:
                - "@contao_manager.config.auth"
            calls:
                - [setContainer, ["@service_container"]]

    contao_manager.controller.config_composer:
            class: Contao\ManagerApi\Controller\ConfigController
            arguments:
                - "@contao_manager.config.composer"
            calls:
                - [setContainer, ["@service_container"]]

    contao_manager.controller.config_manager:
        class: Contao\ManagerApi\Controller\ManagerConfigController
        arguments:
            - "@contao_manager.config.manager"
            - "@contao_manager.i18n.translator"
        calls:
            - [setContainer, ["@service_container"]]

    contao_manager.controller.config_users:
            class: Contao\ManagerApi\Controller\UserController
            arguments:
                - "@contao_manager.config.user"
            calls:
                - [setContainer, ["@service_container"]]
