services:
    contao_manager.controller.status:
        class: Contao\ManagerApi\Controller\StatusController
        arguments:
            - "@tenside.status"
            - "@contao_manager.self_test"
        calls:
            - [setContainer, ["@service_container"]]

    contao_manager.controller.config:
        class: Contao\ManagerApi\Controller\ConfigController
        arguments:
            - "@tenside.home"
            - "@filesystem"
        calls:
            - [setContainer, ["@service_container"]]
