services:
    contao_manager.listener.security:
        class: Contao\ManagerApi\EventListener\SecurityListener
        arguments:
            - "@contao_manager.security.jwt_manager"
            - "@security.token_storage"
            - "@security.authorization_checker"
        tags:
            - { name: kernel.event_listener, event: kernel.request }
            - { name: kernel.event_listener, event: kernel.response }

    contao_manager.listener.json_request:
        class: Contao\ManagerApi\EventListener\JsonRequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 100 }
