cyon.ch:
    name: cyon GmbH
    website: www.cyon.ch
    last_update: 2017-05-31
    issues: []
    php:
        - /opt/alt/php{major}{minor}/usr/bin/php

inetrobots.com:
    name: Hostingwerk (Feyer Media GmbH & Co. KG)
    website: www.hostingwerk.de
    last_update: 2017-06-13
    issues: []
    php:
        - /usr/bin/php-{major}.{minor}

ispgateway.de:
    name: Host Europe GmbH
    website: www.hosteurope.de
    last_update: 2017-05-31
    issues: []
    php:
        - /usr/local/bin/php{major}-{major}{minor}LATEST-CLI

rzone.de:
    name: Strato AG
    website: www.strato.de
    last_update: 2017-05-31
    issues: [memory]

sui-inter.net:
    name: Metanet AG
    website: www.metanet.ch
    last_update: 2017-05-31
    issues: []
    php:
        - /opt/php{major}{minor}/bin/php
        - /usr/bin/php

tophost.ch:
    name: Novatrend Services GmbH
    website: www.novatrend.ch
    last_update: 2017-05-31
    issues: [cputime]
    php:
        - /usr/local/bin/php

uberspace.de:
    name: Uberspace
    website: www.uberspace.de
    last_update: 2017-07-12
    issues: []

vhost.io:
    name: Hostingwerk (Feyer Media GmbH & Co. KG)
    website: www.hostingwerk.de
    last_update: 2017-06-13
    issues: []
    php:
        - /usr/bin/php-{major}.{minor}
