status:
    path: /api/status
    defaults: { _controller: contao_manager.controller.status }
    methods: [GET]

login:
    path:     /api/session
    defaults: { _controller: contao_manager.controller.session:login }
    methods:  [POST]

logout:
    path:     /api/session
    defaults: { _controller: contao_manager.controller.session:logout }
    methods:  [DELETE]

users_list:
    path:     /api/users
    defaults: { _controller: contao_manager.controller.users:listUsers }
    methods:  [GET]

users_create:
    path:     /api/users
    defaults: { _controller: contao_manager.controller.users:createUser }
    methods:  [POST]

user_get:
    path:     /api/users/{username}
    defaults: { _controller: contao_manager.controller.users:retrieveUser }
    methods:  [GET]

user_put:
    path:     /api/users/{username}
    defaults: { _controller: contao_manager.controller.users:replaceUser }
    methods:  [PUT]

user_delete:
    path:     /api/users/{username}
    defaults: { _controller: contao_manager.controller.users:deleteUser }
    methods:  [DELETE]





install_configure:
    path:     /api/install/configure
    defaults: { _controller: TensideCoreBundle:InstallProject:configure }
    methods:  [POST]

install_create_project:
    path:     /api/install/create-project
    defaults: { _controller: TensideCoreBundle:InstallProject:createProject }
    methods:  [POST]

packages_get:
    path:     /api/packages
    defaults: { _controller: TensideCoreBundle:Package:packageList }
    methods:  [GET]

constraint_check:
    path:     /api/constraint
    defaults: { _controller: TensideCoreBundle:VersionConstraint:checkVersionConstraint }
    methods:  [POST]

tasks_get:
    path:     /api/tasks
    defaults: { _controller: TensideCoreBundle:TaskRunner:getTasks }
    methods:  [GET]

tasks_run:
    path:     /api/tasks/run
    defaults: { _controller: TensideCoreBundle:TaskRunner:run }
    methods:  [GET]

task_get:
    path:     /api/tasks/{taskId}
    defaults: { _controller: TensideCoreBundle:TaskRunner:getTask }
    methods:  [GET]
    requirements:
        taskId: "[a-z0-9]+"

task_add:
    path:     /api/tasks
    defaults: { _controller: TensideCoreBundle:TaskRunner:addTask }
    methods:  [POST]

task_delete:
    path:     /api/tasks/{taskId}
    defaults: { _controller: TensideCoreBundle:TaskRunner:deleteTask }
    methods:  [DELETE]
    requirements:
        taskId: "[a-z0-9]+"
