session:
    path: /api/session
    defaults: { _controller: Contao\ManagerApi\Controller\SessionController }
    methods: [GET, POST, DELETE]

files:
    path:     /api/files/{file}
    defaults: { _controller: Contao\ManagerApi\Controller\FileController }
    methods:  [GET, PUT, DELETE]


##############
#   Server   #
##############

server_selfupdate:
    path:     /api/server/self-update
    defaults: { _controller: Contao\ManagerApi\Controller\Server\SelfUpdateController }
    methods:  [GET]

server_config:
    path:     /api/server/config
    defaults: { _controller: Contao\ManagerApi\Controller\Server\ConfigController }
    methods:  [GET, PUT]

server_php_web:
    path:     /api/server/php-web
    defaults: { _controller: Contao\ManagerApi\Controller\Server\PhpWebController }
    methods:  [GET]

server_php_cli:
    path:     /api/server/php-cli
    defaults: { _controller: Contao\ManagerApi\Controller\Server\PhpCliController }
    methods:  [GET]

server_composer:
    path:     /api/server/composer
    defaults: { _controller: Contao\ManagerApi\Controller\Server\ComposerController }
    methods:  [GET]

server_contao:
    path:     /api/server/contao
    defaults: { _controller: Contao\ManagerApi\Controller\Server\ContaoController }
    methods:  [GET]

server_phpinfo:
    path:     /api/server/phpinfo
    defaults: { _controller: Contao\ManagerApi\Controller\Server\PhpinfoController }
    methods:  [GET]

server_opcache:
    path:     /api/server/opcache
    defaults: { _controller: Contao\ManagerApi\Controller\Server\OpcacheController }
    methods:  [GET, DELETE]


#############
#   Users   #
#############

users_list:
    path:     /api/users
    defaults: { _controller: Contao\ManagerApi\Controller\UserController:listUsers }
    methods:  [GET]

users_create:
    path:     /api/users
    defaults: { _controller: Contao\ManagerApi\Controller\UserController:createUser }
    methods:  [POST]

user_get:
    path:     /api/users/{username}
    defaults: { _controller: Contao\ManagerApi\Controller\UserController:retrieveUser }
    methods:  [GET]

user_put:
    path:     /api/users/{username}
    defaults: { _controller: Contao\ManagerApi\Controller\UserController:replaceUser }
    methods:  [PUT]

user_delete:
    path:     /api/users/{username}
    defaults: { _controller: Contao\ManagerApi\Controller\UserController:deleteUser }
    methods:  [DELETE]

tokens_get:
    path:     /api/users/{username}/tokens
    defaults: { _controller: Contao\ManagerApi\Controller\UserController:listTokens }
    methods:  [GET]

tokens_create:
    path:     /api/users/{username}/tokens
    defaults: { _controller: Contao\ManagerApi\Controller\UserController:createToken }
    methods:  [POST]

token_get:
    path:     /api/users/{username}/tokens/{token}
    defaults: { _controller: Contao\ManagerApi\Controller\UserController:retrieveToken }
    methods:  [GET]

token_delete:
    path:     /api/users/{username}/tokens/{token}
    defaults: { _controller: Contao\ManagerApi\Controller\UserController:deleteToken }
    methods:  [DELETE]


#####################
#   Configuration   #
#####################

config_manager:
    path:     /api/config/manager
    defaults: { _controller: contao_manager.controller.config_manager }
    methods:  [GET, PUT, PATCH]

config_auth:
    path:     /api/config/auth
    defaults: { _controller: contao_manager.controller.config_auth }
    methods:  [GET, PUT, PATCH]

config_auth_github:
    path:     /api/config/auth/github-oauth
    defaults: { _controller: contao_manager.controller.config_auth:putGithubToken }
    methods:  [PUT]

config_composer:
    path:     /api/config/composer
    defaults: { _controller: contao_manager.controller.config_composer }
    methods:  [GET, PUT, PATCH]


##################
#   Contao API   #
##################

contao_access_key:
    path:     /api/contao/access-key
    defaults: { _controller: Contao\ManagerApi\Controller\Contao\AccessKeyController }
    methods:  [GET, PUT, DELETE]


#############
#   Tasks   #
#############

task:
    path:     /api/task
    defaults: { _controller: Contao\ManagerApi\Controller\TaskController }
    methods:  [GET, PUT, PATCH, DELETE]


###############
#   Tenside   #
###############

packages_get:
    path:     /api/packages
    defaults: { _controller: TensideCoreBundle:Package:packageList }
    methods:  [GET]

constraint_check:
    path:     /api/constraint
    defaults: { _controller: TensideCoreBundle:VersionConstraint:checkVersionConstraint }
    methods:  [POST]
