status:
    path: /api/status
    defaults: { _controller: contao_manager.controller.status }
    methods: [GET]

login:
    path:     /api/session
    defaults: { _controller: contao_manager.controller.session:login }
    methods:  [POST]

logout:
    path:     /api/session
    defaults: { _controller: contao_manager.controller.session:logout }
    methods:  [DELETE]



#############
#   Users   #
#############

users_list:
    path:     /api/users
    defaults: { _controller: contao_manager.controller.users:listUsers }
    methods:  [GET]

users_create:
    path:     /api/users
    defaults: { _controller: contao_manager.controller.users:createUser }
    methods:  [POST]

user_get:
    path:     /api/users/{username}
    defaults: { _controller: contao_manager.controller.users:retrieveUser }
    methods:  [GET]

user_put:
    path:     /api/users/{username}
    defaults: { _controller: contao_manager.controller.users:replaceUser }
    methods:  [PUT]

user_delete:
    path:     /api/users/{username}
    defaults: { _controller: contao_manager.controller.users:deleteUser }
    methods:  [DELETE]



#####################
#   Configuration   #
#####################

config_manager_get:
    path:     /api/config/manager
    defaults: { _controller: contao_manager.controller.config_manager:getAction }
    methods:  [GET]

config_manager_put:
    path:     /api/config/manager
    defaults: { _controller: contao_manager.controller.config_manager:putAction }
    methods:  [PUT]

config_manager_patch:
    path:     /api/config/manager
    defaults: { _controller: contao_manager.controller.config_manager:patchAction }
    methods:  [PATCH]

config_auth_get:
    path:     /api/config/auth
    defaults: { _controller: contao_manager.controller.config_auth:getAction }
    methods:  [GET]

config_auth_put:
    path:     /api/config/auth
    defaults: { _controller: contao_manager.controller.config_auth:putAction }
    methods:  [PUT]

config_auth_patch:
    path:     /api/config/auth
    defaults: { _controller: contao_manager.controller.config_auth:patchAction }
    methods:  [PATCH]

config_auth_github:
    path:     /api/config/auth/github-oauth
    defaults: { _controller: contao_manager.controller.config_auth:putGithubToken }
    methods:  [PUT]

config_composer_get:
    path:     /api/config/composer
    defaults: { _controller: contao_manager.controller.config_composer:getAction }
    methods:  [GET]

config_composer_put:
    path:     /api/config/composer
    defaults: { _controller: contao_manager.controller.config_composer:putAction }
    methods:  [PUT]

config_composer_patch:
    path:     /api/config/composer
    defaults: { _controller: contao_manager.controller.config_composer:patchAction }
    methods:  [PATCH]



###############
#   Tenside   #
###############

install_create_project:
    path:     /api/install/create-project
    defaults: { _controller: TensideCoreBundle:InstallProject:createProject }
    methods:  [POST]

packages_get:
    path:     /api/packages
    defaults: { _controller: TensideCoreBundle:Package:packageList }
    methods:  [GET]

constraint_check:
    path:     /api/constraint
    defaults: { _controller: TensideCoreBundle:VersionConstraint:checkVersionConstraint }
    methods:  [POST]

tasks_get:
    path:     /api/tasks
    defaults: { _controller: TensideCoreBundle:TaskRunner:getTasks }
    methods:  [GET]

tasks_run:
    path:     /api/tasks/run
    defaults: { _controller: TensideCoreBundle:TaskRunner:run }
    methods:  [GET]

task_get:
    path:     /api/tasks/{taskId}
    defaults: { _controller: TensideCoreBundle:TaskRunner:getTask }
    methods:  [GET]
    requirements:
        taskId: "[a-z0-9]+"

task_add:
    path:     /api/tasks
    defaults: { _controller: TensideCoreBundle:TaskRunner:addTask }
    methods:  [POST]

task_delete:
    path:     /api/tasks/{taskId}
    defaults: { _controller: TensideCoreBundle:TaskRunner:deleteTask }
    methods:  [DELETE]
    requirements:
        taskId: "[a-z0-9]+"
