session:
    path: /api/session
    defaults: { _controller: Contao\ManagerApi\Controller\SessionController }
    methods: [GET, POST, DELETE]

files:
    path:     /api/files/{file}
    defaults: { _controller: Contao\ManagerApi\Controller\FileController }
    methods:  [GET, PUT, DELETE]


##############
#   Server   #
##############

server_selfupdate:
    path:     /api/server/self-update
    defaults: { _controller: Contao\ManagerApi\Controller\System\SelfUpdateController }
    methods:  [GET]

server_config:
    path:     /api/server/config
    defaults: { _controller: Contao\ManagerApi\Controller\System\ConfigController }
    methods:  [GET, PUT]

server_php_web:
    path:     /api/server/php-web
    defaults: { _controller: Contao\ManagerApi\Controller\System\PhpWebController }
    methods:  [GET]

server_php_cli:
    path:     /api/server/php-cli
    defaults: { _controller: Contao\ManagerApi\Controller\System\PhpCliController }
    methods:  [GET]

server_composer:
    path:     /api/server/composer
    defaults: { _controller: Contao\ManagerApi\Controller\System\ComposerController }
    methods:  [GET]

server_contao:
    path:     /api/server/contao
    defaults: { _controller: Contao\ManagerApi\Controller\System\ContaoController }
    methods:  [GET]

server_phpinfo:
    path:     /api/server/phpinfo
    defaults: { _controller: Contao\ManagerApi\Controller\System\PhpinfoController }
    methods:  [GET]

#############
#   Users   #
#############

users_list:
    path:     /api/users
    defaults: { _controller: contao_manager.controller.users:listUsers }
    methods:  [GET]

users_create:
    path:     /api/users
    defaults: { _controller: contao_manager.controller.users:createUser }
    methods:  [POST]

user_get:
    path:     /api/users/{username}
    defaults: { _controller: contao_manager.controller.users:retrieveUser }
    methods:  [GET]

user_put:
    path:     /api/users/{username}
    defaults: { _controller: contao_manager.controller.users:replaceUser }
    methods:  [PUT]

user_delete:
    path:     /api/users/{username}
    defaults: { _controller: contao_manager.controller.users:deleteUser }
    methods:  [DELETE]



#####################
#   Configuration   #
#####################

config_manager_get:
    path:     /api/config/manager
    defaults: { _controller: contao_manager.controller.config_manager:getAction }
    methods:  [GET]

config_manager_put:
    path:     /api/config/manager
    defaults: { _controller: contao_manager.controller.config_manager:putAction }
    methods:  [PUT]

config_manager_patch:
    path:     /api/config/manager
    defaults: { _controller: contao_manager.controller.config_manager:patchAction }
    methods:  [PATCH]

config_auth_get:
    path:     /api/config/auth
    defaults: { _controller: contao_manager.controller.config_auth:getAction }
    methods:  [GET]

config_auth_put:
    path:     /api/config/auth
    defaults: { _controller: contao_manager.controller.config_auth:putAction }
    methods:  [PUT]

config_auth_patch:
    path:     /api/config/auth
    defaults: { _controller: contao_manager.controller.config_auth:patchAction }
    methods:  [PATCH]

config_auth_github:
    path:     /api/config/auth/github-oauth
    defaults: { _controller: contao_manager.controller.config_auth:putGithubToken }
    methods:  [PUT]

config_composer_get:
    path:     /api/config/composer
    defaults: { _controller: contao_manager.controller.config_composer:getAction }
    methods:  [GET]

config_composer_put:
    path:     /api/config/composer
    defaults: { _controller: contao_manager.controller.config_composer:putAction }
    methods:  [PUT]

config_composer_patch:
    path:     /api/config/composer
    defaults: { _controller: contao_manager.controller.config_composer:patchAction }
    methods:  [PATCH]


#############
#   Tasks   #
#############

task_get:
    path:     /api/task
    defaults: { _controller: contao_manager.controller.tasks:getTask }
    methods:  [GET]

task_put:
    path:     /api/task
    defaults: { _controller: contao_manager.controller.tasks:putTask }
    methods:  [PUT]

task_delete:
    path:     /api/task
    defaults: { _controller: contao_manager.controller.tasks:deleteTask }
    methods:  [DELETE]

task_status:
    path:     /api/task/status
    defaults: { _controller: contao_manager.controller.tasks:putTaskStatus }
    methods:  [PUT]

###############
#   Tenside   #
###############

packages_get:
    path:     /api/packages
    defaults: { _controller: TensideCoreBundle:Package:packageList }
    methods:  [GET]

constraint_check:
    path:     /api/constraint
    defaults: { _controller: TensideCoreBundle:VersionConstraint:checkVersionConstraint }
    methods:  [POST]
