status:
    path: /api/status
    defaults: { _controller: contao_manager.controller.status:statusAction }
    methods: [GET]


TensideCoreBundle:
    resource: "@TensideCoreBundle/Resources/config/routing.yml"
    prefix: /api
