services:
    contao_manager.self_test:
        class: Tenside\Core\SelfTest\SelfTest
        calls:
            - [addTest, ['@contao_manager.self_test.file_owner']]
            - [addTest, ['@contao_manager.self_test.url_fopen']]
            - [addTest, ['@contao_manager.self_test.env']]
            - [addTest, ['@contao_manager.self_test.spawn']]
            - [addTest, ['@contao_manager.self_test.cli_runtime']]
            - [addTest, ['@contao_manager.self_test.cli_arguments']]
            #- [addTest, ['@contao_manager.self_test.cli_fork']]
            - [addTest, ['@contao_manager.self_test.cli_os']]

    contao_manager.self_test.file_owner:
        class: Tenside\Core\SelfTest\Generic\SelfTestFileOwnerMatches

    contao_manager.self_test.url_fopen:
        class: Tenside\Core\SelfTest\Php\SelfTestAllowUrlFopenEnabled

    contao_manager.self_test.env:
        class: Tenside\Core\SelfTest\Php\SelfTestEnvPopulated

    contao_manager.self_test.spawn:
        class: Tenside\Core\SelfTest\Cli\SelfTestCanSpawnProcesses

    contao_manager.self_test.cli_runtime:
        class: Tenside\Core\SelfTest\Cli\SelfTestCliRuntime

    contao_manager.self_test.cli_arguments:
        class: Tenside\Core\SelfTest\Cli\SelfTestCliArguments

    contao_manager.self_test.cli_fork:
        class: Tenside\Core\SelfTest\Cli\SelfTestCliCanFork

    contao_manager.self_test.cli_os:
        class: Tenside\Core\SelfTest\Cli\SelfTestCliOsChecks
