imports:
    - { resource: controllers.yml }
    - { resource: selftest.yml }

services:
    contao_manager.config.auth:
        class: Contao\ManagerApi\Config\AuthConfig
        arguments:
            - "@kernel"
            - "@filesystem"

    contao_manager.config.composer:
        class: Contao\ManagerApi\Config\ComposerConfig
        arguments:
            - "@kernel"
            - "@filesystem"

    contao_manager.config.manager:
        class: Contao\ManagerApi\Config\ManagerConfig
        arguments:
            - "@kernel"
            - "@filesystem"

    contao_manager.config.user:
        class: Contao\ManagerApi\Config\UserConfig
        arguments:
            - "@kernel"
            - "@security.password_encoder"
            - "@filesystem"

    contao_manager.security.jwt_manager:
        class: Contao\ManagerApi\Security\JwtManager
        arguments:
            - "@contao_manager.config.manager"

    contao_manager.security.jwt_authenticator:
        class: Contao\ManagerApi\Security\JwtAuthenticator
        arguments:
            - "@contao_manager.security.jwt_manager"

    contao_manager.security.user_provider:
        class: Symfony\Component\Security\Core\User\InMemoryUserProvider
        factory: [Contao\ManagerApi\Security\UserProviderFactory, createUserProvider]
        arguments:
            - "@contao_manager.config.user"


    app.taskfactory:
        class:     Contao\ManagerApi\Tenside\TaskFactory
        arguments: ["@tenside.home", "@tenside.config"]
        tags:
            - { name: tenside.taskfactory }

    app.command.background_task:
        class: Terminal42\BackgroundProcess\Command\ProcessRunnerCommand
        tags:
            - { name: console.command }

###
# Override Tenside services to adjust for Contao Manager
###

    tenside.home:
        class:  Contao\ManagerApi\Tenside\HomePathDeterminator
        synthetic: true

    tenside.config:
        class:          Tenside\Core\Config\TensideJsonConfig
        factory:        [Contao\ManagerApi\Tenside\JsonConfigFactory, create]
        arguments:      ["@tenside.home"]
        public:         true

    tenside.status:
        class:     Contao\ManagerApi\Tenside\InstallationStatusDeterminator
        arguments:
            - "@contao_manager.config.user"
            - "@tenside.home"
        public: true
