services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $debug: '%kernel.debug%'
            $cliIntegrityChecks: !tagged app.integrity.cli
            $webIntegrityChecks: !tagged app.integrity.web
            $serverConfigFile: '%kernel.root_dir%/Resources/config/servers.yml'

    Contao\ManagerApi\:
        resource: ../../{Command,Config,Controller,EventListener,IntegrityCheck,Process,Security,System,Task/Composer/,Task/Contao,Task/Manager,Task/Packages}


    ####################
    #  Named services  #
    ####################

    contao_manager.security.user_provider:
        class: Symfony\Component\Security\Core\User\InMemoryUserProvider
        factory: [Contao\ManagerApi\Security\UserProviderFactory, createUserProvider]


    ##############################
    #  Additional configuration  #
    ##############################

    kernel:
        class: Contao\ManagerApi\ApiKernel
        synthetic: true
        autowire: false

    Contao\ManagerApi\Composer\CloudResolver:
        tags:
            - { name: monolog.logger, channel: tasks }

    Contao\ManagerApi\Composer\Environment: ~

    Contao\ManagerApi\Process\ConsoleProcessFactory:
        tags:
            - { name: monolog.logger, channel: tasks }

    Contao\ManagerApi\Task\TaskManager:
        arguments:
            - !tagged app.task
        tags:
            - { name: monolog.logger, channel: tasks }

    Terminal42\BackgroundProcess\Command\ProcessRunnerCommand: ~
