services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false
        bind:
            $debug: '%kernel.debug%'
            $serverConfigFile: '%kernel.root_dir%/Resources/config/servers.yml'

    Contao\ManagerApi\:
        resource: ../../{Config,EventListener,IntegrityCheck,Process,I18n,Security,System,Task/Composer/,Task/Contao,Task/Manager,Task/Packages}

    Contao\ManagerApi\Command\:
        resource: ../../Command
        public: true

    Contao\ManagerApi\Controller\:
        resource: ../../Controller
        public: true


    ####################
    #  Named services  #
    ####################

    contao_manager.security.user_provider:
        class: Symfony\Component\Security\Core\User\InMemoryUserProvider
        factory: [Contao\ManagerApi\Security\UserProviderFactory, createUserProvider]


    ##############################
    #  Additional configuration  #
    ##############################

    Contao\ManagerApi\ApiKernel: '@kernel'

    locale_listener:
        class: Contao\ManagerApi\EventListener\LocaleListener
        tags: [{ name: kernel.event_subscriber }]

    Contao\ManagerApi\Composer\CloudResolver:
        calls:
            - ['setLogger', ['@logger']]
        tags:
            - { name: monolog.logger, channel: tasks }

    Contao\ManagerApi\Composer\Environment: ~

    Contao\ManagerApi\Process\ConsoleProcessFactory:
        tags:
            - { name: monolog.logger, channel: tasks }

    Contao\ManagerApi\Process\ContaoApi: ~

    Contao\ManagerApi\Process\ContaoConsole: ~

    Contao\ManagerApi\Task\TaskManager:
        arguments:
            - !tagged app.task
        tags: [{ name: monolog.logger, channel: tasks }]
