imports:
    - { resource: controllers.yml }

services:
    contao_manager.config.auth:
        class: Contao\ManagerApi\Config\AuthConfig
        arguments:
            - "@kernel"
            - "@filesystem"

    contao_manager.config.composer:
        class: Contao\ManagerApi\Config\ComposerConfig
        arguments:
            - "@kernel"
            - "@filesystem"

    contao_manager.config.manager:
        class: Contao\ManagerApi\Config\ManagerConfig
        arguments:
            - "@kernel"
            - "@filesystem"

    contao_manager.config.user:
        class: Contao\ManagerApi\Config\UserConfig
        arguments:
            - "@kernel"
            - "@security.password_encoder"
            - "@filesystem"

    contao_manager.i18n.translator:
        class: Contao\ManagerApi\I18n\Translator
        arguments:
            - "@request_stack"

    contao_manager.integrity.allow_url_fopen:
        class: Contao\ManagerApi\IntegrityCheck\AllowUrlFopenCheck
        arguments:
            - "@contao_manager.i18n.translator"

    contao_manager.integrity.contao:
        class: Contao\ManagerApi\IntegrityCheck\ContaoCheck
        arguments:
            - "@kernel"
            - "@contao_manager.process.contao_api"
            - "@contao_manager.i18n.translator"
            - "@filesystem"

    contao_manager.integrity.openssl:
        class: Contao\ManagerApi\IntegrityCheck\OpenSSLCheck
        arguments:
            - "@contao_manager.i18n.translator"

    contao_manager.integrity.process:
        class: Contao\ManagerApi\IntegrityCheck\ProcessCheck
        arguments:
            - "@contao_manager.i18n.translator"

    contao_manager.integrity.web_root:
        class: Contao\ManagerApi\IntegrityCheck\WebRootCheck
        arguments:
            - "@contao_manager.i18n.translator"

    contao_manager.integrity.windows:
        class: Contao\ManagerApi\IntegrityCheck\WindowsPlatformCheck
        arguments:
            - "@contao_manager.i18n.translator"

    contao_manager.process.console_factory:
        class: Contao\ManagerApi\Process\ConsoleProcessFactory
        arguments:
            - "@kernel"
            - "@contao_manager.config.manager"
            - "@logger"

    contao_manager.process.contao_api:
        class: Contao\ManagerApi\Process\ContaoApi
        arguments:
            - "@contao_manager.process.console_factory"

    contao_manager.security.jwt_manager:
        class: Contao\ManagerApi\Security\JwtManager
        arguments:
            - "@contao_manager.config.manager"

    contao_manager.security.jwt_authenticator:
        class: Contao\ManagerApi\Security\JwtAuthenticator
        arguments:
            - "@contao_manager.security.jwt_manager"

    contao_manager.security.user_provider:
        class: Symfony\Component\Security\Core\User\InMemoryUserProvider
        factory: [Contao\ManagerApi\Security\UserProviderFactory, createUserProvider]
        arguments:
            - "@contao_manager.config.user"




    app.taskfactory:
        class:     Contao\ManagerApi\Tenside\TaskFactory
        arguments:
            - "@kernel"
            - "@contao_manager.process.console_factory"
        tags:
            - { name: tenside.taskfactory }

    app.command.background_task:
        class: Terminal42\BackgroundProcess\Command\ProcessRunnerCommand
        tags:
            - { name: console.command }

###
# Override Tenside services to adjust for Contao Manager
###

    tenside.home:
        class:  Contao\ManagerApi\Tenside\HomePathDeterminator
        arguments:
            - "@kernel"

    tenside.config:
        class:          Tenside\Core\Config\TensideJsonConfig
        factory:        [Contao\ManagerApi\Tenside\JsonConfigFactory, create]
        arguments:      ["@tenside.home"]
        public:         true

    tenside.status:
        class:     Contao\ManagerApi\Tenside\InstallationStatusDeterminator
        arguments:
            - "@contao_manager.config.user"
            - "@tenside.home"
        public: true
