services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false
        bind:
            $debug: '%kernel.debug%'
            $serverConfigFile: '%kernel.root_dir%/Resources/config/servers.yml'

    Contao\ManagerApi\:
        resource: '../../*'
        exclude: '../../{Command,Controller,Resources,Tests}'

    Contao\ManagerApi\Command\:
        resource: '../../Command'
        public: true

    Contao\ManagerApi\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']


    ####################
    #  Named services  #
    ####################

    contao_manager.security.user_provider:
        class: Symfony\Component\Security\Core\User\InMemoryUserProvider
        factory: [Contao\ManagerApi\Security\UserProviderFactory, createUserProvider]


    ##############################
    #  Additional configuration  #
    ##############################

    Contao\ManagerApi\ApiKernel: '@kernel'

    locale_listener:
        class: Contao\ManagerApi\EventListener\LocaleListener

    Contao\ManagerApi\Task\TaskManager:
        arguments:
            - !tagged app.task
